### ISSUE TITLE
Proposition of display the list of news

### ISSUE THREAD

**Issue by Mystelven** [satlive/website#14]
Because for now, the <code>tag</code> is not very visible. 
(In fact, I just payed attention few minutes ago.)

Why we don't put the tag on the same line as the title (with a `margin : 5px;` for when we are on smartphone) like this : 

![list](https://cloud.githubusercontent.com/assets/5182636/8356668/fbc7e454-1b56-11e5-926d-5699ca6be0ab.png)

We can also put an assigned color of label for each tag, to be able to recognize them from far.
It will be more attractive for the eye.

**Comment by satlive** [comment]
Good idea. PR welcome :)

**Comment by Mystelven** [comment]
This feature is now available in the merge #20 ! ;)
