### ISSUE TITLE
broken link for book "problème SAT" on home page

### ISSUE THREAD

**Issue by fgrieu** [satlive/website#2]
The link for the "problème SAT" book (on right, bottom of http://www.satlive.org/) is broken.
It is currently to
http://www.lavoisier.fr/notice/fr423832.html
That should be to
http://www.lavoisier.fr/livre/mathematiques/probleme-sat-progres-et-defis/sais/descriptif-9782746218864

**Comment by sat4j** [comment]
Fixed. Thanks for reporting the problem.

**Comment by satlive** [comment]
Thanks for reporting the issue.
