### ISSUE TITLE
XML feed contains links to localhost

### ISSUE THREAD

**Issue by heitorPB** [satlive/website#58]
The current deployed [feed.xml](http://www.satlive.org/feed.xml) contains several links to `localhost:4000`, but it should be `http://www.satlive.org/` instead.

How was the site built?

**Comment by satlive** [comment]
As usual, using `jekyll serve`

I had to update to the latest version of jekyll two days ago. Maybe something changed in a recent release?

**Comment by satlive** [comment]
I just used `jekyll build` instead.

I checked the feed.xml file. It no longer contains any reference to localhost.

**Comment by heitorPB** [comment]
`jekyll build` is the way to go. Thank you for the quick response.

Have a nice day!

**Comment by satlive** [comment]
Your are welcome.

I let you close the issue if the problem is solved.
