### ISSUE TITLE
The <li> in the navigation should be "active"

### ISSUE THREAD

**Issue by Mystelven** [satlive/website#8]
The part of code generated in the file "_includes/header.html" by this part : 

<ul class="nav navbar-nav">
        {% for page in site.pages %}
          {% if page.title %}
           <li><a href="{{ page.url | prepend: site.baseurl }}">{{ page.title }}</a></li>
          {% endif %}
        {% endfor %}
      </ul>

Should put an 'class="active"' on the "li" where we are currently on.

**Comment by satlive** [comment]
I partly fixed it. I still have an issue for the home link. Not sure how to fix it.

**Comment by Mystelven** [comment]
Well it's completely fixed. Making "active" the Home is not necessary needed.

The goal is to give a feedback about the fact that the page changed. 

The fact that when we are on "Home", the other are not "active" is also a feedback :)

**Comment by Mystelven** [comment]
In fact, it could have be "more fixed", and it's now the case in the merge #21
